networks:
  local-kafka:
    external: true
  ollama-docker:
    external: true

services:
  prompt-generator:
    image: reels-automation-prompt-generator
    networks:
      - local-kafka
      - ollama-docker
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_IP: ${OLLAMA_IP}
      KAFKA_BROKER_DOCKER: ${KAFKA_BROKER_DOCKER}
      OLLAMA_IP_DOCKER: ${OLLAMA_IP_DOCKER}
    stdin_open: true   
    tty: true         
